### ISSUE TITLE
Memory region used by mc-mapping

### ISSUE THREAD

**Issue by soramichi** [heechul/palloc#9]
Hi,

thank you so much for making great research software publicly available. I really appreciate it.

`mc-mapping.c` uses a memory region starting from a physical address of `0x1000000080000000` for mmap'ing, but my machine somewhat uses this range thus the contents of `list` are changed immediately after they are written.

Is there any special reason to specifically use `0x1000000080000000`? Or can I just use some different address in order to avoid memory regions used by the system? The machine has a single-socket Core i9-7900X (Skylake-X) and 4 DIMMs.

Thanks for your time and effort,

Soramichi

**Update**: the same happens even if I remove 3 of the DIMMs so that the machine has only 1 DIMM.

**Update 2**: I noticed that `0x1000000080000000` is approximately 10^18, which must not be used by the system because no machine has that large memory. I guess I'm still missing something.

**Comment by heechul** [comment]
This issue should be merged with the #10
